name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    lint-and-build:
        name: Lint, Type Check & Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run lint

            - name: Type check
              run: npm run type-check

            - name: Build projects
              run: npm run build

            - name: Run tests
              run: npm run test

    deploy-preview:
        name: Deploy Preview
        runs-on: ubuntu-latest
        needs: lint-and-build
        if: github.event_name == 'pull_request'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy to Vercel Preview
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  working-directory: ./apps/web

    deploy-production:
        name: Deploy Production
        runs-on: ubuntu-latest
        needs: lint-and-build
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy to Vercel Production
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-args: "--prod"
                  working-directory: ./apps/web
