#!/bin/bash

# 🚀 Netlify Deployment - Step-by-Step Interactive Guide
# This script helps you deploy to Netlify

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║           🚀 NETLIFY DEPLOYMENT GUIDE                                ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}📋 STEP 1: GitHub Repository${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Code pushed to GitHub:"
echo "   Repository: https://github.com/EmanuelRad169/digiprintplus-website.git"
echo "   Branch: main"
echo ""

echo -e "${BLUE}📋 STEP 2: Connect to Netlify${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://app.netlify.com"
echo ""
echo "Then:"
echo "  1. Click 'Add new site' → 'Import an existing project'"
echo "  2. Choose 'GitHub'"
echo "  3. Select: EmanuelRad169/digiprintplus-website"
echo "  4. Choose branch: main"
echo ""
read -p "Press ENTER when you've connected the repository..."
echo ""

echo -e "${BLUE}📋 STEP 3: Configure Build Settings${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In the Netlify setup wizard, configure:"
echo ""
echo -e "${GREEN}Build command:${NC} npm run build:netlify"
echo -e "${GREEN}Publish directory:${NC} apps/web/out"
echo -e "${GREEN}Base directory:${NC} (leave empty or use: .)"
echo ""
read -p "Press ENTER when you've set the build configuration..."
echo ""

echo -e "${BLUE}📋 STEP 4: Set Environment Variables${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Before deploying, you MUST set these environment variables:"
echo ""
echo "Go to: Site settings → Environment variables → Add a variable"
echo ""
echo -e "${YELLOW}Required variables:${NC}"
echo ""
echo "Variable: NEXT_PUBLIC_SANITY_PROJECT_ID"
echo "Value: as5tildt"
echo ""
echo "Variable: NEXT_PUBLIC_SANITY_DATASET"
echo "Value: production"
echo ""
echo "Variable: NEXT_PUBLIC_SANITY_API_VERSION"
echo "Value: 2024-01-01"
echo ""
echo -e "${RED}Variable: SANITY_API_TOKEN${NC}"
echo -e "${YELLOW}Value: Get from https://www.sanity.io/manage${NC}"
echo "  1. Go to Sanity.io → Manage → Your Project"
echo "  2. Click 'API' → 'Tokens'"
echo "  3. Click 'Add API token'"
echo "  4. Name: 'Netlify Production'"
echo "  5. Permissions: Viewer (read)"
echo "  6. Copy the token"
echo ""
echo "Variable: NEXT_PUBLIC_SITE_URL"
echo -e "${YELLOW}Value: Your Netlify URL (e.g., https://your-site.netlify.app)${NC}"
echo "  (You'll get this URL after first deploy, can update later)"
echo ""
read -p "Press ENTER when you've added all environment variables..."
echo ""

echo -e "${BLUE}📋 STEP 5: Deploy!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click 'Deploy site' in Netlify!"
echo ""
echo "This will:"
echo "  • Pull your code from GitHub"
echo "  • Run: npm run build:netlify"
echo "  • Generate 301+ static pages"
echo "  • Deploy to CDN"
echo ""
echo "⏱️  Build time: ~3-5 minutes"
echo ""
read -p "Press ENTER to continue when deploy starts..."
echo ""

echo -e "${BLUE}📋 STEP 6: Monitor Build${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Watch the build logs in Netlify dashboard"
echo ""
echo "✅ Look for these success indicators:"
echo "  • 'npm run build:netlify' starts"
echo "  • 'Collecting page data' appears"
echo "  • 'Generating static pages' shows progress"
echo "  • 'Finalizing page optimization' completes"
echo "  • 'Deploy succeeded!' appears"
echo ""
echo "❌ If build fails, check for:"
echo "  • Missing environment variables"
echo "  • TypeScript errors"
echo "  • Memory issues"
echo ""
read -p "Press ENTER when build completes successfully..."
echo ""

echo -e "${BLUE}📋 STEP 7: Update Site URL${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After first deploy:"
echo ""
echo "1. Copy your Netlify URL (e.g., https://your-site.netlify.app)"
echo "2. Go to: Site settings → Environment variables"
echo "3. Update: NEXT_PUBLIC_SITE_URL with your actual Netlify URL"
echo "4. Click 'Trigger deploy' → 'Clear cache and deploy site'"
echo ""
read -p "Press ENTER after updating the URL..."
echo ""

echo -e "${BLUE}📋 STEP 8: Verify Deployment${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Enter your Netlify URL to verify:"
read -p "URL: " SITE_URL
echo ""

if [ -z "$SITE_URL" ]; then
    echo -e "${YELLOW}⚠️  No URL provided, skipping verification${NC}"
else
    echo "Testing deployment..."
    echo ""
    npx tsx scripts/verify-deployment.ts "$SITE_URL"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║           ✅ DEPLOYMENT COMPLETE!                                    ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}🎉 Your site is now live on Netlify!${NC}"
echo ""
echo "📝 Next steps:"
echo "  • Test all pages on your live site"
echo "  • Set up custom domain (optional)"
echo "  • Configure Netlify functions (if needed)"
echo "  • Set up continuous deployment"
echo ""
echo "📚 Resources:"
echo "  • Netlify Dashboard: https://app.netlify.com"
echo "  • Build logs: Check in Netlify UI"
echo "  • Environment variables: Site settings → Environment variables"
echo ""
